### ISSUE TITLE
nixops-auto-upgrade generates long store paths

### ISSUE THREAD

**Issue by priegger** [kampka/nix-packages#7]
Logged error:

error: The path name 'd4v7p21va9g92by6q2njllr81qmwldfn-gchpqyqaykqb53008a1n3p58rv0z26f9-8cr3w23zy8im7l5ad25l306n0am2pcqj-vmi7z1bhayp483896zr792j5z2639vhm-r95jjq24xy379km9ypx8xfqd3riw02pg-vwnzp303f30ddkgxzpn4fismxlww5i18-r0fk89ip9yi7s5nqcq5kgn4cwh50c311-home' is invalid: name must be less than 212 characters. Path names are alphanumeric and can include the symbols +-._?= and must not begin with a period. Note: If 'd4v7p21va9g92by6q2njllr81qmwldfn-gchpqyqaykqb53008a1n3p58rv0z26f9-8cr3w23zy8im7l5ad25l306n0am2pcqj-vmi7z1bhayp483896zr792j5z2639vhm-r95jjq24xy379km9ypx8xfqd3riw02pg-vwnzp303f30ddkgxzpn4fismxlww5i18-r0fk89ip9yi7s5nqcq5kgn4cwh50c311-home' is a source file and you cannot rename it on disk, builtins.path { name = ... } can be used to give it an alternative name.

The initial directory with my nixos config is home, so the store entry hash1-home is created. The daily nixops-auto-upgrade seems to use the nix store path, so a new store path is created with hash2-hash1-home and so on and so on.

**Comment by kampka** [comment]
Fixed in 9a2ef9f3abd95d22d44f1952180684612b785e27
